-- Phase 1 quote detail catalog fields and seed data.

alter table public.service_items
  add column if not exists category text,
  add column if not exists standardizable boolean not null default true,
  add column if not exists photo_guide text,
  add column if not exists included_items jsonb not null default '[]'::jsonb,
  add column if not exists excluded_items jsonb not null default '[]'::jsonb,
  add column if not exists warranty_policy text,
  add column if not exists standard_material_sku text,
  add column if not exists premium_material_sku text,
  add column if not exists addon_skus jsonb not null default '[]'::jsonb;

insert into public.materials (sku, name, category, wholesale_price, retail_price, stock_quantity, is_active)
values
  ('toilet_standard', '일반형 양변기', 'bathroom', 65000, 90000, 20, true),
  ('toilet_premium', '고급형 치마형 양변기', 'bathroom', 145000, 220000, 10, true),
  ('faucet_standard', '일반 수전', 'kitchen', 45000, 70000, 20, true),
  ('faucet_premium', '프리미엄 수전', 'kitchen', 95000, 150000, 10, true),
  ('light_standard', '일반 LED 등기구', 'lighting', 25000, 45000, 30, true),
  ('light_premium', '고급 LED 등기구', 'lighting', 65000, 100000, 12, true),
  ('outlet_standard', '일반 콘센트', 'electric', 8000, 15000, 50, true),
  ('outlet_premium', '고급 콘센트', 'electric', 18000, 30000, 30, true),
  ('bidet_standard', '비데 설치 기본 부속', 'bathroom', 18000, 30000, 20, true),
  ('bidet_premium', '비데 설치 고급 부속', 'bathroom', 35000, 60000, 10, true),
  ('handle_standard', '일반 도어 핸들', 'door', 18000, 35000, 20, true),
  ('handle_premium', '고급 도어 핸들', 'door', 42000, 70000, 10, true),
  ('ventilator_standard', '일반 욕실 환풍기', 'bathroom', 35000, 60000, 20, true),
  ('ventilator_premium', '저소음 환풍기', 'bathroom', 85000, 130000, 10, true),
  ('angle_valve', '앵글밸브 교체', 'addon', 7000, 15000, 50, true),
  ('bidet_hose', '비데 호스 교체', 'addon', 6000, 12000, 50, true),
  ('silicone_finish', '방수 실리콘 마감', 'addon', 8000, 15000, 40, true),
  ('waste_disposal', '폐기물 수거', 'addon', 10000, 20000, 30, true)
on conflict (sku) do update
set
  name = excluded.name,
  category = excluded.category,
  wholesale_price = excluded.wholesale_price,
  retail_price = excluded.retail_price,
  stock_quantity = excluded.stock_quantity,
  is_active = excluded.is_active,
  updated_at = now();

insert into public.service_items (
  service_type_code,
  display_name,
  base_price,
  estimated_minutes,
  is_active,
  metadata,
  category,
  standardizable,
  photo_guide,
  included_items,
  excluded_items,
  warranty_policy,
  standard_material_sku,
  premium_material_sku,
  addon_skus
)
values
  (
    'toilet_replace',
    '변기 교체',
    80000,
    120,
    true,
    '{"category":"bathroom"}'::jsonb,
    'bathroom',
    true,
    '변기 전체 / 문제 부위 / 배관·규격이 보이는 사진',
    '["기존 철거", "신규 설치", "누수 테스트", "1년 A/S"]'::jsonb,
    '["타일 보수", "배관 이설", "폐기물 대량 처리"]'::jsonb,
    '시공 하자 1년 무상 A/S',
    'toilet_standard',
    'toilet_premium',
    '["angle_valve", "bidet_hose", "silicone_finish", "waste_disposal"]'::jsonb
  ),
  (
    'faucet_replace',
    '수전 교체',
    70000,
    90,
    true,
    '{"category":"kitchen"}'::jsonb,
    'kitchen',
    true,
    '수전 전체 / 하부 배관 / 싱크대 아래 연결부 사진',
    '["기존 철거", "신규 설치", "누수 테스트", "1년 A/S"]'::jsonb,
    '["싱크볼 교체", "배관 이설"]'::jsonb,
    '시공 하자 1년 무상 A/S',
    'faucet_standard',
    'faucet_premium',
    '["angle_valve", "silicone_finish"]'::jsonb
  ),
  (
    'light_replace',
    '전등 교체',
    40000,
    40,
    true,
    '{"category":"lighting"}'::jsonb,
    'lighting',
    true,
    '등기구 전체 / 스위치 / 천장 고정부 사진',
    '["기존 철거", "신규 설치", "점등 테스트", "1년 A/S"]'::jsonb,
    '["배선 증설", "스위치 신설"]'::jsonb,
    '시공 하자 1년 무상 A/S',
    'light_standard',
    'light_premium',
    '["waste_disposal"]'::jsonb
  ),
  (
    'outlet_replace',
    '콘센트 교체',
    35000,
    30,
    true,
    '{"category":"electric"}'::jsonb,
    'electric',
    true,
    '콘센트 정면 / 주변 벽면 / 차단기 위치 사진',
    '["기존 철거", "신규 설치", "전원 테스트", "1년 A/S"]'::jsonb,
    '["전기 배선 증설", "누전 수리"]'::jsonb,
    '시공 하자 1년 무상 A/S',
    'outlet_standard',
    'outlet_premium',
    '[]'::jsonb
  ),
  (
    'bidet_install',
    '비데 설치',
    45000,
    45,
    true,
    '{"category":"bathroom"}'::jsonb,
    'bathroom',
    true,
    '변기 전체 / 급수 밸브 / 콘센트 위치 사진',
    '["제품 설치", "급수 연결", "작동 테스트", "1년 A/S"]'::jsonb,
    '["전기 콘센트 신설", "비데 제품 구매"]'::jsonb,
    '시공 하자 1년 무상 A/S',
    'bidet_standard',
    'bidet_premium',
    '["bidet_hose", "angle_valve"]'::jsonb
  ),
  (
    'door_handle',
    '도어 핸들 교체',
    35000,
    30,
    true,
    '{"category":"door"}'::jsonb,
    'door',
    true,
    '문 전체 / 손잡이 앞뒤 / 잠금장치 측면 사진',
    '["기존 철거", "신규 설치", "잠금 테스트", "1년 A/S"]'::jsonb,
    '["문틀 보수", "도어 교체"]'::jsonb,
    '시공 하자 1년 무상 A/S',
    'handle_standard',
    'handle_premium',
    '[]'::jsonb
  ),
  (
    'ventilator_replace',
    '환풍기 교체',
    70000,
    80,
    true,
    '{"category":"bathroom"}'::jsonb,
    'bathroom',
    true,
    '환풍기 전체 / 천장 타공부 / 전원 스위치 사진',
    '["기존 철거", "신규 설치", "동작 테스트", "1년 A/S"]'::jsonb,
    '["천장 보수", "배선 이설"]'::jsonb,
    '시공 하자 1년 무상 A/S',
    'ventilator_standard',
    'ventilator_premium',
    '["waste_disposal"]'::jsonb
  )
on conflict (service_type_code) do update
set
  display_name = excluded.display_name,
  base_price = excluded.base_price,
  estimated_minutes = excluded.estimated_minutes,
  is_active = excluded.is_active,
  metadata = excluded.metadata,
  category = excluded.category,
  standardizable = excluded.standardizable,
  photo_guide = excluded.photo_guide,
  included_items = excluded.included_items,
  excluded_items = excluded.excluded_items,
  warranty_policy = excluded.warranty_policy,
  standard_material_sku = excluded.standard_material_sku,
  premium_material_sku = excluded.premium_material_sku,
  addon_skus = excluded.addon_skus;
